# Generated by Django 5.2.12 on 2026-04-20 22:15

import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey
import uuid
from django.db import migrations, models

from sentry.new_migrations.migrations import CheckedMigration


class Migration(CheckedMigration):
    # This flag is used to mark that a migration shouldn't be automatically run in production.
    # This should only be used for operations where it's safe to run the migration after your
    # code has deployed. So this should not be used for most operations that alter the schema
    # of a table.
    # Here are some things that make sense to mark as post deployment:
    # - Large data migrations. Typically we want these to be run manually so that they can be
    #   monitored and not block the deploy for a long period of time while they run.
    # - Adding indexes to large tables. Since this can take a long time, we'd generally prefer to
    #   run this outside deployments so that we don't block them. Note that while adding an index
    #   is a schema change, it's completely safe to run the operation after the code has deployed.
    # Once deployed, run these manually via: https://develop.sentry.dev/database-migrations/#migration-deployment

    is_post_deployment = False

    dependencies = [
        ("seer", "0007_add_extras_to_nightshiftrun"),
        ("sentry", "1070_increase_integration_external_id_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeerRun",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("seer_run_state_id", models.TextField()),
                ("user_id", models.BigIntegerField(null=True)),
                ("type", models.CharField(max_length=32)),
                ("last_triggered_at", models.DateTimeField()),
                ("extras", models.JSONField(db_default={}, default=dict)),
                (
                    "organization",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentry.organization",
                    ),
                ),
            ],
            options={
                "db_table": "seer_seerrun",
            },
        ),
        migrations.CreateModel(
            name="SeerAgentRun",
            fields=[
                (
                    "id",
                    sentry.db.models.fields.bounded.BoundedBigAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=256)),
                ("source", models.CharField(max_length=64)),
                ("extras", models.JSONField(db_default={}, default=dict)),
                (
                    "group",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sentry.group",
                    ),
                ),
                (
                    "project",
                    sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sentry.project",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent",
                        to="seer.seerrun",
                    ),
                ),
            ],
            options={
                "db_table": "seer_seeragentrun",
            },
        ),
        migrations.AddIndex(
            model_name="seerrun",
            index=models.Index(fields=["user_id"], name="seer_seerru_user_id_d68c82_idx"),
        ),
        migrations.AddIndex(
            model_name="seerrun",
            index=models.Index(
                fields=["organization", "-last_triggered_at"],
                name="seer_seerru_organiz_c90199_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seerrun",
            index=models.Index(
                fields=["organization", "type", "-last_triggered_at"],
                name="seer_seerru_organiz_eb75f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="seerrun",
            index=models.Index(fields=["last_triggered_at"], name="seer_seerru_last_tr_9581cc_idx"),
        ),
        migrations.AddConstraint(
            model_name="seerrun",
            constraint=models.UniqueConstraint(
                fields=("seer_run_state_id",), name="seerrun_unique_seer_run_state_id"
            ),
        ),
        migrations.AddIndex(
            model_name="seeragentrun",
            index=models.Index(fields=["source"], name="seer_seerag_source_8aaa3a_idx"),
        ),
    ]
